version: 0.2

phases:
  install:
    commands:
      - echo Installing backend modules...
      - npm ci --only=production
      - echo Install frontend modules...
      - cd client && npm ci
  build:
    commands:
      - echo Building static files for client...
      - npm run build
artifacts:
  files:
    - ./*
    - node_modules/**/*
    - client/build/**/*